/* Generated by Together */

import java.util.Vector;

class Customer {

    /**
     * @clientCardinality 1
     * @supplierCardinality 0..* 
     */
    private Order linkOrder;
    private Vector orders;
    private String address;
    private String salutation;
    private String name;
    private String faxNumber;
    private Vector customerProperties;
    private String emailAddress;
    private String recentPurchase;
    private int preferedMailingSystem; // 0 = regular mail  1 = email
    private String customerID;

    public Customer() {
        setLinkOrder(new Order());
        setOrders(new Vector());
        setAddress("");
        setSalutation("");
        setName("");
        setFaxNumber("");
        setCustomerProperties(new Vector());
        setEmailAddress("");
        setRecentPurchase("");
        setPreferedMailingSystem(0);
        setCustomerID("");
    }
    
    public Customer(Order LinkOrder, Vector Orders, String Address, String Salutation, 
            String Name, String FaxNumber, Vector CustomerProperties, String EmailAddress, 
            String RecentPurchase, int PreferedMailingSystem, String CustID) {
        setLinkOrder(LinkOrder);
        setOrders(Orders);
        setAddress(Address);
        setSalutation(Salutation);
        setName(Name);
        setFaxNumber(FaxNumber);
        setCustomerProperties(CustomerProperties);
        setEmailAddress(EmailAddress);
        setRecentPurchase(RecentPurchase);
        setPreferedMailingSystem(PreferedMailingSystem);
        setCustomerID(CustID);
    }    
    
    public void setLinkOrder(Order O) {
        linkOrder = O;
    }
    
    public void setOrders(Vector V) {
        orders = V;
    }
    
    public void setAddress(String S) {
        address = S;
    }
    
    public void setSalutation(String S) {
        salutation = S;
    }
    
    public void setName(String S) {
        name = S;
    }
    
    public void setFaxNumber(String S) {
        faxNumber = S;
    }
    
    public void setCustomerProperties(Vector V) {
        customerProperties = V;
    }
    
    public void setEmailAddress(String S) {
        emailAddress = S;
    }
    
    public void setRecentPurchase(String S) {
        recentPurchase = S;
    }
    
    public void setPreferedMailingSystem(int i) {
        preferedMailingSystem = i;
    }
    
    public void setCustomerID(String S) {
        customerID = S;
    }    
    
    public Order getLinkOrder() {
        return linkOrder;
    }
    
    public Vector getOrders() {
        return orders;
    }
    
    public String getAddress() {
        return address;
    }
    
    public String getSalutation() {
        return salutation;
    }
    
    public String getName() {
        return name;
    }
    
    public String getFaxNumber() {
        return faxNumber;
    }
    
    public Vector getCustomerProperties() {
        return customerProperties;
    }
    
    public String getEmailAddress() {
        return emailAddress;
    }
    
    public String getRecentPurchase() {
        return recentPurchase;
    }
    
    public int getPreferedMailingSystem() {
        return preferedMailingSystem;
    }
    
    public String getCustomerID() {
        return customerID;
    }
    
    
/*    
    public Order getLastRecentOrder() {
    }
*/
}
